version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:6.2.6-v7
    restart: on-failure
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/data

volumes:
  redis: